# Generated by Django 4.2.4 on 2023-09-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_remove_inquiry_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
