# Generated by Django 4.2.4 on 2023-10-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0003_inquiry_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
