# Generated by Django 4.2.4 on 2023-10-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
