# Generated by Django 4.2.4 on 2023-10-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_remove_message_sender_message_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='customer_need',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='message',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
