# Generated by Django 4.2.4 on 2023-10-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_message_city_message_customer_need_message_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
    ]
