# Generated by Django 4.2.4 on 2023-10-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_alter_message_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='subject',
            new_name='product_name',
        ),
    ]
