services:
  - name: web
    buildCommand: python manage.py collectstatic --noinput
    buildDir: /opt/render/project/src

env:
  - key: DJANGO_SETTINGS_MODULE
    value: "carseller.settings"

environments:
  - name: primary
    DJANGO_MEDIA_ROOT: /mnt/data/media/