services:
  - name: web
    buildCommand: python manage.py collectstatic --noinput
    buildDir: /Desktop/PythonProjects/car-website2

env:
  - key: DJANGO_SETTINGS_MODULE
    value: "carseller.settings"

environments:
  - name: primary
    DJANGO_MEDIA_ROOT: '/PythonProjects/car-website2/media'