# Generated by Django 4.2.4 on 2023-10-17 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_designation_team_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Phone_number',
            field=models.CharField(max_length=255, validators=[django.core.validators.MaxLengthValidator(255)]),
        ),
        migrations.AlterField(
            model_name='team',
            name='facebook_link',
            field=models.URLField(max_length=100, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='team',
            name='first_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MaxLengthValidator(255)]),
        ),
        migrations.AlterField(
            model_name='team',
            name='google_plus_link',
            field=models.URLField(max_length=100, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='team',
            name='last_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MaxLengthValidator(255)]),
        ),
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter_link',
            field=models.URLField(max_length=100, validators=[django.core.validators.URLValidator()]),
        ),
    ]
