# Generated by Django 4.1.13 on 2024-02-20 09:52

import cars.models
import ckeditor.fields
import datetime
import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_title', models.CharField(max_length=255)),
                ('brand_slug', models.SlugField(choices=[('bmw', 'B.M.W'), ('toyota', 'TOYOTA'), ('volkswagen', 'VOLKSWAGEN'), ('morbius', 'MORBIUS'), ('honda', 'HONDA'), ('mazda', 'Mazda'), ('subaru', 'Subaru'), ('mercedes', 'Mercedes'), ('audi', 'Audi'), ('nissan', 'Nissan'), ('hyundai', 'Hyundai'), ('chevrolet', 'Chevrolet'), ('nissan', 'Nissan')], max_length=200)),
                ('city', models.CharField(choices=[('nairobi', 'Nairobi'), ('eldoret', 'Eldoret'), ('mombasa', 'Mombasa'), ('kisumu', 'Kisumu'), ('nakuru', 'Nakuru')], max_length=100)),
                ('color', models.CharField(choices=[('red', 'RED'), ('white', 'WHITE'), ('black', 'BLACK'), ('green', 'GREEN'), ('grey', 'GREY'), ('blue', 'BLUE')], max_length=100)),
                ('model', models.CharField(choices=[('micro', 'Micro'), ('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('coupe', 'Coupe'), ('sport car', 'Sport car'), ('suv', 'SUV'), ('pickup', 'Pickup'), ('van', 'Van'), ('lorry', 'Lorry')], max_length=100)),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], db_index=True, verbose_name='year')),
                ('condition', models.CharField(max_length=100)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('video_link', models.URLField(blank=True, help_text='Include your video link!', null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('car_photo', models.ImageField(upload_to='photos/%Y/%m/%d/', validators=[cars.models.validate_image_file_extension])),
                ('car_photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', validators=[cars.models.validate_image_file_extension])),
                ('car_photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', validators=[cars.models.validate_image_file_extension])),
                ('car_photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', validators=[cars.models.validate_image_file_extension])),
                ('car_photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', validators=[cars.models.validate_image_file_extension])),
                ('car_photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', validators=[cars.models.validate_image_file_extension])),
                ('car_photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', validators=[cars.models.validate_image_file_extension])),
                ('car_photo_7', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', validators=[cars.models.validate_image_file_extension])),
                ('car_video', models.FileField(blank=True, help_text='Upload a video of the car.', null=True, upload_to='videos/%Y/%m/%d/', validators=[cars.models.validate_video_file_extension])),
                ('features', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Cruise Control', 'Cruise Control'), ('Audio Interface', 'Audio Interface'), ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('Seat Heating', 'Seat Heating'), ('Alarm System', 'Alarm System'), ('ParkAssist', 'ParkAssist'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Wind Deflector', 'Wind Deflector'), ('Bluetooth Handset', 'Bluetooth Handset')], max_length=255)),
                ('body_style', models.CharField(max_length=100)),
                ('engine', models.CharField(max_length=100)),
                ('transmission', models.CharField(max_length=100)),
                ('interior', models.CharField(max_length=100)),
                ('miles', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('doors', models.CharField(choices=[('2', '2'), ('4', '4')], max_length=10)),
                ('vin_no', models.CharField(max_length=100, unique=True)),
                ('milage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fuel_type', models.CharField(choices=[('petroleum', 'PETROLEUM'), ('diesel', 'DIESEL')], max_length=50)),
                ('no_of_owners', models.CharField(max_length=100, validators=[django.core.validators.validate_integer])),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
