# Generated by Django 4.1.13 on 2024-02-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='video_link',
            field=models.URLField(blank=True, help_text='Include your video link here!', null=True),
        ),
    ]
