# Generated by Django 4.2.4 on 2023-08-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_brand_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='doors',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petroleum', 'PETROLEUM'), ('diesel', 'DIESEL')], default='', max_length=50),
        ),
    ]
