# Generated by Django 4.2.4 on 2023-08-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_doors_alter_car_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('red', 'RED'), ('black', 'BLACK'), ('green', 'GREEN'), ('grey', 'GREY'), ('blue', 'BLUE')], max_length=100),
        ),
    ]
