# Generated by Django 4.2.4 on 2023-08-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petroleum', 'PETROLEUM'), ('diesel', 'DIESEL')], max_length=50),
        ),
    ]
