# Generated by Django 4.2.4 on 2023-08-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_car_brand_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vin_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
