# Generated by Django 4.2.4 on 2023-08-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_car_vin_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('red', 'RED'), ('white', 'WHITE'), ('black', 'BLACK'), ('green', 'GREEN'), ('grey', 'GREY'), ('blue', 'BLUE')], max_length=100),
        ),
    ]
