# Generated by Django 4.2.4 on 2023-08-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_remove_car_state_alter_car_brand_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand_slug',
            field=models.SlugField(choices=[('bmw', 'B.M.W'), ('toyota', 'TOYOTA'), ('volkswagen', 'VOLKSWAGEN'), ('morbius', 'MORBIUS'), ('honda', 'HONDA'), ('mazda', 'Mazda'), ('subaru', 'Subaru'), ('mercedes', 'Mercedes'), ('audi', 'Audi'), ('nissan', 'Nissan'), ('hyundai', 'Hyundai'), ('chevrolet', 'Chevrolet'), ('nissan', 'Nissan')], max_length=200),
        ),
    ]
