# Generated by Django 4.2.4 on 2023-08-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_alter_car_brand_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(choices=[('nairobi', 'Nairobi'), ('eldoret', 'Eldoret'), ('mombasa', 'Mombasa'), ('kisumu', 'Kisumu'), ('nakuru', 'Nakuru')], max_length=100),
        ),
    ]
