# Generated by Django 4.2.4 on 2023-09-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_alter_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='video_link',
            field=models.URLField(blank=True, help_text='Enter a link to the video', max_length=255, null=True),
        ),
    ]
