# Generated by Django 4.2.4 on 2023-09-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_car_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_photo_5',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_photo_6',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_photo_7',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='video_link',
            field=models.URLField(blank=True, help_text='Enter a link to the video', null=True),
        ),
    ]
