# Generated by Django 4.2.4 on 2023-09-11 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_car_car_photo_5_car_car_photo_6_car_car_photo_7_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='video_link',
        ),
    ]
