# Generated by Django 4.2.4 on 2023-09-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0020_car_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='video_link',
            field=models.URLField(blank=True, help_text='Include your video link!', null=True),
        ),
    ]
