# Generated by Django 4.2.4 on 2023-09-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0021_alter_car_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_video',
            field=models.FileField(blank=True, help_text='Upload a video of the car.', null=True, upload_to='videos/%Y/%m/%d/'),
        ),
    ]
