# Generated by Django 4.2.7 on 2024-01-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_registration', '0004_alter_adminuser_email_alter_adminuser_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminuser',
            old_name='full_name',
            new_name='fullname',
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.CharField(max_length=300),
        ),
    ]
