# Generated by Django 4.2.7 on 2023-12-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_registration', '0004_alter_adminuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
