# Generated by Django 4.2.7 on 2024-01-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_registration', '0005_alter_adminuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='full_name',
            field=models.CharField(blank=True, default=0, max_length=100),
            preserve_default=False,
        ),
    ]
