# Generated by Django 4.2.7 on 2024-01-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_registration', '0006_alter_adminuser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
