# Generated by Django 4.1.13 on 2024-02-20 09:59

import datetime
import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Accessory Name')),
                ('color', models.CharField(choices=[('red', 'RED'), ('white', 'WHITE'), ('black', 'BLACK'), ('green', 'GREEN'), ('gray', 'GRAY'), ('blue', 'BLUE'), ('beige', 'BEIGE'), ('blue', 'BROWN'), ('yellow', 'YELLOW'), ('orange', 'ORANGE'), ('silver', 'SILVER'), ('carbon fiber', 'CARBON FIBER')], max_length=255, verbose_name='Color')),
                ('category', models.CharField(choices=[('Interior Accessories', 'Interior Accessories'), ('Exterior Accessories', 'Exterior Accessories'), ('Perfomance Accessories', 'Perfomance Accessories'), ('Safety and Security Accessories', 'Safety and Security Accessories'), ('Electronics and Entertainment', 'Electronics and Entertainment'), ('Lighting Accessories', 'Lighting Accessories'), ('Utility Accessories', 'Utility Accessories'), ('Appearance Accessories', 'Appearance Accessories')], max_length=500)),
                ('type_slug', models.SlugField(choices=[('floor-mats', 'Floor-Mats'), ('liners', 'liners'), ('seat-covers', 'Seat-Covers'), ('seat-cushions', 'Seat-Cushions'), ('steering-wheel-covers', 'Steering-Wheel-Covers'), ('sunshades', 'Sunshades'), ('dash-covers', 'Dash-Covers'), ('car-covers', 'Car-Covers'), ('roof-racks', 'Roof-Racks'), ('bike-racks', 'Bike-Racks'), ('running-boards', 'Running-Boards'), ('fender-flares', 'Fender-Flares'), ('air-filters', 'Air-Filters'), ('exhaust-systems', 'Exhaust-Systems'), ('tuning-chips', 'Tuning-Chips'), ('suspension-upgrades', 'Suspension-Upgrades'), ('performance-brakes', 'Performance-Brakes'), ('car-stereos', 'Car-Stereos'), ('backup-cameras', 'Backup-Cameras'), ('bluetooth-kits', 'Bluetooth-Kits'), ('dash-cams', 'Dash-Cams'), ('alarm-systems', 'Alarm-Systems'), ('car-safety-kits', 'Car-Safety-Kits'), ('parking-sensors', 'Parking-Sensors'), ('blind-spot-mirrors', 'Blind-Spot-Mirrors'), ('locking-wheel-nuts', 'Locking-Wheel-Nuts'), ('led-headlights', 'LED-Headlights'), ('fog-lights', 'Fog-Lights'), ('interior-led-lights', 'Interior-LED-Lights'), ('underglow-lights', 'Underglow-Lights'), ('light-bars', 'Light-Bars'), ('cargo-organizers', 'Cargo-Organizers'), ('car-hitches', 'Car-Hitches'), ('tire-inflators', 'Tire-Inflators'), ('car-tents', 'Car-Tents'), ('tool-kits', 'Tool-Kits'), ('chrome-trim', 'Chrome-Trim'), ('window-tinting', 'Window-Tinting'), ('body-kits', 'Body-Kits'), ('grille-guards', 'Grille-Guards'), ('vinyl-decals', 'Vinyl-Decals'), ('car-covers', 'Car-covers')], max_length=500)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('accessory_photo', models.ImageField(blank=True, null=True, upload_to='accessories/%Y/%m/%d/', validators=[django.core.validators.validate_image_file_extension], verbose_name='Image')),
                ('features', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Adjustability', 'Adjustability'), ('Heating and Cooling', 'Heating and Cooling'), ('Smart Technology', 'Smart Technology'), ('Wireless Charging', 'Wireless Charging'), ('Waterproof and Weatherproof', 'Waterproof and Weatherproof'), ('LED Lighting', 'LED Lighting'), ('Noise Reduction', 'Noise Reduction'), ('Remote Control', 'Remote Control'), ('Safety Features', 'Safety Features'), ('Durability', 'Durability'), ('Easy Installation', 'Easy Installation'), ('Customization', 'Customization'), ('Quick Release', 'Quick Release'), ('Safety Reflectors', 'Safety Reflectors'), ('Anti-Theft Measures', 'Anti-Theft Measures'), ('UV Protection', 'UV Protection'), ('Ventilation', 'Ventilation'), ('Stain Resistance', 'Stain Resistance'), ('Compatibility', 'Compatibility'), ('Multi-Functionality', 'Multi-Functionality')], max_length=300, verbose_name='Features')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_special', models.BooleanField(default=False, verbose_name='Is Special')),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
