# Generated by Django 4.2.4 on 2023-09-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_products', '0004_feature_alter_accessories_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='features',
            field=models.ManyToManyField(blank=True, to='our_products.feature'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(choices=[('Adjustability', 'Adjustability'), ('Heating and Cooling', 'Heating and Cooling'), ('Smart Technology', 'Smart Technology'), ('Wireless Charging', 'Wireless Charging'), ('Waterproof and Weatherproof', 'Waterproof and Weatherproof'), ('LED Lighting', 'LED Lighting'), ('Noise Reduction', 'Noise Reduction'), ('Remote Control', 'Remote Control'), ('Safety Features', 'Safety Features'), ('Durability', 'Durability'), ('Easy Installation', 'Easy Installation'), ('Customization', 'Customization'), ('Quick Release', 'Quick Release'), ('Safety Reflectors', 'Safety Reflectors'), ('Anti-Theft Measures', 'Anti-Theft Measures'), ('UV Protection', 'UV Protection'), ('Ventilation', 'Ventilation'), ('Stain Resistance', 'Stain Resistance'), ('Compatibility', 'Compatibility'), ('Multi-Functionality', 'Multi-Functionality')], max_length=300, verbose_name='Feature Names'),
        ),
    ]
