# Generated by Django 4.2.4 on 2023-09-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_products', '0009_alter_accessories_type_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='type_slug',
            field=models.SlugField(choices=[('Floor Mats', 'Floor-Mats'), ('liners', 'liners'), ('Seat Covers', 'Seat-Covers'), ('Seat cushions', 'Seat-Cushions'), ('Steering Wheel Covers', 'Steering-Wheel-Covers'), ('Sunshades', 'Sunshades'), ('Dash Covers', 'Dash-Covers'), ('Car Covers', 'Car-Covers'), ('Roof Racks', 'Roof-Racks'), ('Bike Racks', 'Bike-Racks'), ('Running Boards', 'Running-Boards'), ('Fender Flares', 'Fender-Flares'), ('Air Filters', 'Air-Filters'), ('Exhaust Systems', 'Exhaust-Systems'), ('Tuning Chips', 'Tuning-Chips'), ('Suspension Upgrades', 'Suspension-Upgrades'), ('Performance Brakes', 'Performance-Brakes'), ('Car Stereos', 'Car-Stereos'), ('Backup Cameras', 'Backup-Cameras'), ('Bluetooth Kits', 'Bluetooth-Kits'), ('Dash Cams', 'Dash-Cams'), ('Alarm Systems', 'Alarm-Systems'), ('Car Safety Kits', 'Car-Safety-Kits'), ('Parking Sensors', 'Parking-Sensors'), ('Blind Spot Mirrors', 'Blind-Spot-Mirrors'), ('Locking Wheel Nuts', 'Locking-Wheel-Nuts'), ('LED Headlights', 'LED-Headlights'), ('Fog Lights', 'Fog-Lights'), ('Interior LED Lights', 'Interior-LED-Lights'), ('Underglow Lights', 'Underglow-Lights'), ('Light Bars', 'Light-Bars'), ('Cargo Organizers', 'Cargo-Organizers'), ('Car Hitches', 'Car-Hitches'), ('Tire Inflators', 'Tire-Inflators'), ('Car Tents', 'Car-Tents'), ('Tool Kits', 'Tool-Kits'), ('Chrome Trim', 'Chrome-Trim'), ('Window Tinting', 'Window-Tinting'), ('Body Kits', 'Body-Kits'), ('Grille Guards', 'Grille-Guards'), ('Vinyl Decals', 'Vinyl-Decals'), ('Car covers', 'Car-covers')], max_length=500),
        ),
    ]
