# Generated by Django 4.2.4 on 2023-09-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_products', '0010_alter_accessories_type_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='type_slug',
            field=models.SlugField(choices=[('floor-mats', 'Floor-Mats'), ('liners', 'liners'), ('seat-covers', 'Seat-Covers'), ('seat-cushions', 'Seat-Cushions'), ('steering-wheel-covers', 'Steering-Wheel-Covers'), ('sunshades', 'Sunshades'), ('dash-covers', 'Dash-Covers'), ('car-covers', 'Car-Covers'), ('roof-racks', 'Roof-Racks'), ('bike-racks', 'Bike-Racks'), ('running-boards', 'Running-Boards'), ('fender-flares', 'Fender-Flares'), ('air-filters', 'Air-Filters'), ('exhaust-systems', 'Exhaust-Systems'), ('tuning-chips', 'Tuning-Chips'), ('suspension-upgrades', 'Suspension-Upgrades'), ('performance-brakes', 'Performance-Brakes'), ('car-stereos', 'Car-Stereos'), ('backup-cameras', 'Backup-Cameras'), ('bluetooth-kits', 'Bluetooth-Kits'), ('dash-cams', 'Dash-Cams'), ('alarm-systems', 'Alarm-Systems'), ('car-safety-kits', 'Car-Safety-Kits'), ('parking-sensors', 'Parking-Sensors'), ('blind-spot-mirrors', 'Blind-Spot-Mirrors'), ('locking-wheel-nuts', 'Locking-Wheel-Nuts'), ('led-headlights', 'LED-Headlights'), ('fog-lights', 'Fog-Lights'), ('interior-led-lights', 'Interior-LED-Lights'), ('underglow-lights', 'Underglow-Lights'), ('light-bars', 'Light-Bars'), ('cargo-organizers', 'Cargo-Organizers'), ('car-hitches', 'Car-Hitches'), ('tire-inflators', 'Tire-Inflators'), ('car-tents', 'Car-Tents'), ('tool-kits', 'Tool-Kits'), ('chrome-trim', 'Chrome-Trim'), ('window-tinting', 'Window-Tinting'), ('body-kits', 'Body-Kits'), ('grille-guards', 'Grille-Guards'), ('vinyl-decals', 'Vinyl-Decals'), ('car-covers', 'Car-covers')], max_length=500),
        ),
    ]
