# Generated by Django 4.2.4 on 2023-09-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('our_products', '0012_accessories_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessories',
            old_name='Accessory_photo',
            new_name='accessory_photo',
        ),
    ]
