# Generated by Django 4.2.4 on 2023-09-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('our_products', '0015_alter_accessories_accessory_photo2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessories',
            name='accessory_photo2',
        ),
    ]
