# Generated by Django 4.2.4 on 2023-09-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_products', '0018_remove_accessories_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='Is Special'),
        ),
    ]
