# Generated by Django 4.2.4 on 2023-10-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_products', '0019_accessories_is_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='color',
            field=models.CharField(choices=[('red', 'RED'), ('white', 'WHITE'), ('black', 'BLACK'), ('green', 'GREEN'), ('gray', 'GRAY'), ('blue', 'BLUE'), ('beige', 'BEIGE'), ('blue', 'BROWN'), ('yellow', 'YELLOW'), ('orange', 'ORANGE'), ('silver', 'SILVER'), ('carbon fiber', 'CARBON FIBER')], default=0, verbose_name='Color'),
            preserve_default=False,
        ),
    ]
