# Generated by Django 4.2.4 on 2023-10-02 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_products', '0020_accessories_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
