# Generated by Django 4.2.4 on 2023-10-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_products', '0021_accessories_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='stock_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock Count'),
        ),
    ]
