# Generated by Django 4.2.4 on 2023-10-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_products', '0022_accessories_stock_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='accessories',
            name='stock_count',
        ),
        migrations.AddField(
            model_name='accessories',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
