# Generated by Django 4.2.4 on 2023-10-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('our_products', '0023_category_remove_accessories_stock_count_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
