# Generated by Django 4.2.4 on 2023-10-16 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('our_products', '0025_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
