# Generated by Django 4.2.4 on 2023-10-17 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_products', '0026_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='accessory_photo',
            field=models.ImageField(blank=True, null=True, upload_to='accessories/%Y/%m/%d/', validators=[django.core.validators.validate_image_file_extension], verbose_name='Image'),
        ),
    ]
