# Generated by Django 4.2.7 on 2023-11-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('our_products', '0027_alter_accessories_accessory_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessories',
            name='created_date',
        ),
    ]
